#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cursive
Version  : 0.2.2
Release  : 20
URL      : https://files.pythonhosted.org/packages/aa/ec/d0e802482530a0b664c910c845cada1e490bc2af568acc0c1ed55c000502/cursive-0.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/aa/ec/d0e802482530a0b664c910c845cada1e490bc2af568acc0c1ed55c000502/cursive-0.2.2.tar.gz
Summary  : Cursive implements OpenStack-specific validation of digital signatures.
Group    : Development/Tools
License  : Apache-2.0
Requires: cursive-license = %{version}-%{release}
Requires: cursive-python = %{version}-%{release}
Requires: cursive-python3 = %{version}-%{release}
Requires: castellan
Requires: cryptography
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : castellan
BuildRequires : cryptography
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.serialization
BuildRequires : oslo.utils
BuildRequires : pbr

%description
===============================
cursive
===============================

Cursive implements OpenStack-specific validation of digital signatures.

As OpenStack continues to mature, robust security controls become increasingly
critical. The cursive project contains code extracted from various OpenStack
projects for verifying digital signatures. Additional capabilities will be
added to this project in support of various security features.

* Free software: Apache license
* Source: http://git.openstack.org/cgit/openstack/cursive
* Bugs: http://bugs.launchpad.net/cursive

Features
--------

* TODO

%package license
Summary: license components for the cursive package.
Group: Default

%description license
license components for the cursive package.


%package python
Summary: python components for the cursive package.
Group: Default
Requires: cursive-python3 = %{version}-%{release}

%description python
python components for the cursive package.


%package python3
Summary: python3 components for the cursive package.
Group: Default
Requires: python3-core
Provides: pypi(cursive)

%description python3
python3 components for the cursive package.


%prep
%setup -q -n cursive-0.2.2
cd %{_builddir}/cursive-0.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582914862
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cursive
cp %{_builddir}/cursive-0.2.2/LICENSE %{buildroot}/usr/share/package-licenses/cursive/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cursive/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
